### ISSUE TITLE
Getting 'Request Unsuccessful' Error

### ISSUE THREAD

**Issue by eereenah-fast** [xchem/enamine-real-search#1]
Hello, thanks a lot for sharing this package! 

I am having trouble executing `session.substructure_search(smiles='C1=CC=C(C=C1)O')` command, as I keep getting the following error:
```
<html style="height:100%"><head><META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW"><meta name="format-detection" content="telephone=no"><meta name="viewport" content="initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><script type="text/javascript" src="/_Incapsula_Resource?SWJIYLWA=719d34d31c8e3a6e6fffd425f7e032f3"></script></head><body style="margin:0px;height:100%"><iframe id="main-iframe" src="/_Incapsula_Resource?CWUDNSAI=23&xinfo=13-82375575-0%200NNN%20RT%281621833744579%204%29%20q%280%20-1%20-1%20-1%29%20r%280%20-1%29%20b1&incident_id=1313000160085196896-322998407081821197&edet=3&cinfo=03000000&pe=100002&rpinfo=0" frameborder=0 width="100%" height="100%" marginheight="0px" marginwidth="0px">Request unsuccessful. Incapsula incident ID: 1313000160085196896-322998407081821197</iframe></body></html>
```

Do you know what may be causing this issue and whether there are any workarounds for it? Thank in advance!

**Comment by matteoferla** [comment]
Unfortunately, Enamine has changed their endpoints to no longer work in an API way, but via cookies — the browser now sends a MarvinJS structure, to which the server returns a Smiles and a session id, this triggers a redirect to /gallery with that session id.

My solution has been switching to the SmallWorld server (https://sw.docking.org/search.html), which can be queried by API. I wrote a [Python wrapper](https://github.com/matteoferla/Python_SmallWorld_API) for it:

    from smallworld_api import SmallWorld  # pip install smallworld-api
    aspirin = 'O=C(C)Oc1ccccc1C(=O)O'
    sw = SmallWorld()
    results : pd.DataFrame = sw.search(aspirin, dist=5, db='REAL_DB_20Q2')

**Comment by eereenah-fast** [comment]
Awesome! Thank you, @matteoferla!
